config/routes.rb
Rails.application.routes.draw do
  resources :catalogues
  resources :books
  resources :users
  devise_for :users, :path => 'u'

  get 'books' => 'books#index'

  get 'collection' => 'users#collection'

  get "test" => "static_page#home"
  get "signup"  => "users#new"

  get "search"  => "books#search", as: :search_books

  authenticated :user do
    root :to => 'books#index', :as => :authenticated_root
  end
  root :to => redirect('/u/sign_in')

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :owner, class_name: User.name, counter_cache: true
  belongs_to :catalogue, counter_cache: true

  attr_accessor :query

  def self.search(query)
    client = Goodreads.new
    client.search_books(query)
  end
end

app/models/catalogue.rb
class Catalogue < ActiveRecord::Base
  validates_uniqueness_of :ISBN
  has_many :books
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  has_many :books, foreign_key: :owner_id

  # validates :name, presence: true, length: {maximum: 50}
  
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # validates :email, presence: true, length: {maximum: 255},
  #                   format: {with: VALID_EMAIL_REGEX},
  #                   uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!


  def new
    @book = Book.new
  end

  def index
    @cat = Catalogue.where("books_count > 0")
    @books = @cat.paginate(page: params[:page], per_page: 24)
  end

  def show

  end

  def search
    @book_results = Book.search(params[:query])
    if @book_results.total_results == "0" || @book_results.nil?
      redirect_to new_book_path(no_results: true)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to collection_path
  end

  def create
    @goodreads_id = params[:goodreads_id]
    @title = params[:title]
    gclient = Goodreads.new
    gbook = gclient.book_by_title(@title)
    @catalogue = Catalogue.new
    @catalogue.title = gbook.title
    @catalogue.ISBN = gbook.isbn
    @catalogue.pages = gbook.num_pages
    @catalogue.author = gbook.authors.author.name
    if gbook.image_url.nil?
      @catalogue.photo = "https://content.redshelf.com/site_media/media/cover_image/default_book_cover.jpg"
    else
      @catalogue.photo = gbook.image_url
    end

    @book = current_user.books.new
    @book.catalogue = @catalogue
    @catalogue.save
    if @book.save
      flash.notice = "#{gbook.title} has been added to your books"
    end
  end
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController
  before_action :authenticate_user!

  def index
    @catalogue = Catalogue.new
    @catalogues = Catalogue.all
  end

  def show
    @hide_searchbar = true
    @catalogue = Catalogue.find(params[:id])
    @user_id = Book.where(catalogue_id: @catalogue.id).select("owner_id")
    @users = User.where(id: @user_id)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    @hide_header = true
    @hide_searchbar = true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def new
    @user = User.new
  end

  def index
    @users = User.all.paginate(page: params[:page], per_page: 12)
  end

  def edit
    @user = current_user
  end


  def show
    @hide_searchbar = true
    @user  = User.find(params[:id])
    @cat_ids = @user.books.pluck(:catalogue_id)
    @cat = Catalogue.where(id: @cat_ids)
  end

  def collection
    @hide_searchbar = true
    @user  = current_user

    @cat_ids = @user.books.pluck(:catalogue_id)
    @cat = Catalogue.where(id: @cat_ids)
  end

  def update
    byebug
    @user = User.find(params[:id])
    @user.update_attributes(clean_params)
  end

  private
  def clean_params
    params.require(:user).permit(:name, :email, :department, :course, :yearofjoining, :hostel)
  end

  def edit
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_catalogue.html.erb
<% @books.each do |cat| %>

  
    <div class="col-md-3 col-lg-2 col-sm-3 col-xs-2 front">
 
    <!-- normal -->
    <div class="ih-item square effect11 top_to_bottom" id="first"><%= link_to catalogue_path(cat) do %>
        <div class="img" id="second"><%= image_tag cat.photo %></div>
        <div class="info" id="third">
          <h3><%= cat.title %></h3>
          <p>Author: <%= cat.author %><br>Language: <%= cat.language %>
              <br>Length: <%= cat.pages %> pages<br>Owned by:<%= cat.books.length %> People<br>Add to Wishlist</p>
        </div>
      <% end %>
    </div>
    <!-- end normal -->

  </div>  


  <% end %>

app/views/books/create.js.erb
alert("Your book has been added")

app/views/books/index.html.erb
<div class="row books_page">
  <%= will_paginate style: 'margin-left:65px' %>
  <div class=" row section books_section">
      <%= render partial: 'books/catalogue'  %>
  </div>  
  <%= will_paginate style: 'margin-left:65px' %>
</div>
    

app/views/books/new.html.erb
<div class="container" id="search-box">
  <h1>Search for  a Book</h1>

<%= form_tag(search_books_path, {:method => :get}) do %>
  <%= text_field_tag :query, '' , class: "form-control", id: "search-input"%>

  <%= submit_tag "Search", class: "btn btn-lg btn-primary"%>
<% end %>

  <% if params[:no_results] %>
    <div id="error-msg" >
      <p style="color: white">No results found</p>
    </div>
    
  <% end %>
</div>

app/views/books/search.html.erb
<h1><%= current_user.name %></h1>

<div class="container">
  <table class="table  table-striped" id="results_table">
  <tbody>
    <tr>
      <th>Book Cover</th>
      <th>Title</th>
      <th>Author</th>
      <th>Publication Year</th>
      <th>Add</th>
    </tr>

  <% @book_results.results.work.each do |book| %>
    <tr>
      <td><img src="<%= book.best_book.image_url %>"></td>
      <td><%= book.best_book.title %></td>
      <td><%= book.best_book.author.name %></td>
      <td><%= book.original_publication_year %></td>
      <td>
        <%= link_to "Add", books_path(goodreads_id: book.id, title: book.best_book.title), method: :post, remote: true, class: "add-btn btn btn-default btn-primary" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/catalogues/index.html.erb
<h1>Hello!</h1>

<%= simple_form_for @catalogue do |f| %>
  <%= f.input :ISBN %>
  <%= f.button :submit %>
<% end %>

app/views/catalogues/show.html.erb
<div class="container">
  <div class="row catalogue_center_box">
    <div class="col-md-6">
      <%= image_tag @catalogue.photo %>
    </div>
    <div class="col-md-6">
      <span class="catalogue_sample"><h3><%= @catalogue.title %></h3>
          <p>Author: <%= @catalogue.author %><br>Language: <%= @catalogue.language %>
              <br>Length: <%= @catalogue.pages %> pages<br>Owned by:<%= Book.all.where(catalogue_id: @catalogue.id).length %> People<br>Add to Wishlist</p>
      </span>
    </div>   
  </div>





  <div class="row owned_by">
    <h3 style = 'color:#fff'>Owned By</h3>
    <% @users.each do |c| %>
      <div class="col-md-4 col-lg-2 col-sm-3 col-xs-2 front">
        <div class="ih-item square effect11 top_to_bottom" id="first"><%= link_to user_path(c) do %>
          <div id="users_page_user_image" ><%= image_tag c.photo %></div>
          <div id="user_details"><span class="card_text"><h4><%= c.name %></h4>Department: <%= c.department %>
            <br> Year Of Joining: <%= c.yearofjoining %><br>Course: <%= c.course %><br>Hostel: <%= c.hostel %> <br> Owns <%= c.books_count.to_i==0 ? ("0 books") : (c.books_count.to_i==1 ? ("1 book"):(c.books_count.to_s + " books")) %> </span>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div> 

</div>


  

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" id="header" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header" id="bookshare">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand" id="brand"><%= link_to 'BOOKSHARE', books_path %></div>
        </div>
        <div id="logo"><%= image_tag("logo.png", :alt => "Bookonnect") %></div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                   <%= link_to 'Books', books_path %>
               </li>
               <li>
                   <%= link_to 'People', users_path %>
               </li>
               <li>
                   <%= link_to 'Profile', user_path(current_user) if current_user %>
               </li>
               <li>
                   <%= link_to 'My Collection', collection_path %>
               </li>

           </ul>
           <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to '+ Add Book', new_book_path, class: "btn btn-default btn-primary" %>
            </li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <% if current_user %>
                    <%= current_user.email %>
                    <% else %>
                    <%=  %>
                    <% end %>
                    <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">

                        <li><%= link_to 'Profile', edit_user_path(current_user) if current_user %>
                        </li>
                        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                        </li>
                        
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/_searchbar.html.erb
<div id="search-tab">
        <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
            </div>
            <!-- <button type="submit" class="btn btn-default">Submit</button> -->
        </form>
        <!-- Single button -->
        <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                Select Genre <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a>
                </li>
                <li><a href="#">Another action</a>
                </li>
                <li><a href="#">Something else here</a>
                </li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a>
                </li>
            </ul>
        </div>
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookonnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookonnect</title>
    <%= favicon_link_tag 'logo.png' %>
    <!-- <link rel="icon" type="image/png" href="app/assets/images/logo.png"> -->
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
</head>
<body class="<%= controller_name %>-<%= action_name %>">


  <% unless @hide_header%>


    <%= render 'layouts/nav' %>
  <% end %>
  
<%= yield %>

</body>
</html>

app/views/static_page/home.html.erb
    
<div class= "container center-box">
  <div class="row title-div"><h1>BooKonnect</h1></div>  

  <div class="row center-div"><p>Books, the best way to make friends. <br> Friends, the best way to find books. <br> Connecting friends and books :) </p></div>
  <div class="buttons">
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn" %>
    <button type="button" class="btn btn-success signup" >Sign Up</button>

    <button type="button" class="btn btn-success login" >Login</button>
  </div>
  
</div>

app/views/users/_user.html.erb
<% @users.each do |c| %>

  <div class="col-md-4 col-lg-2 col-sm-3 col-xs-2 front">
    <!-- normal -->
    <div class="ih-item square effect11 top_to_bottom" id="first"><%= link_to user_path(c) do %>
     <div id="users_page_user_image" ><%= image_tag c.photo %></div>
     <div id="user_details"><span class="card_text"><h4><%= c.name %></h4>Department: <%= c.department %>
      <br> Year Of Joining: <%= c.yearofjoining %><br>Course: <%= c.course %><br>Hostel: <%= c.hostel %> <br> Owns   <%= c.books_count.to_i==0 ? ("0 books") : (c.books_count.to_i==1 ? ("1 book"):(c.books_count.to_s + " books")) %>   </span> </div>
      <% end %>
    </div>
    <!-- end normal -->

  </div>

<% end %>

app/views/users/collection.html.erb
<div class="row books_owned">
      <h3 style = 'color:#fff'>My Collection</h3>
      <% @cat.each do |catal| %>
      
        <div class="col-md-3 col-lg-2 col-sm-3 col-xs-2 front" >
          <div class="ih-item square effect11 top_to_bottom" id="first"><%= link_to catalogue_path(catal) do %>
            <div class="img" id="second"><%= image_tag catal.photo %></div>
            <div class="info" id="third">
              <h3><%= catal.title %></h3>
              <p>Author: <%= catal.author %><br>Language: <%= catal.language %>
                  <br>Length: <%= catal.pages %> pages<br>Owned by:<%= Book.all.where(catalogue_id: catal.id).length %> People<br>Add to Wishlist
              </p>
              
            </div>
          <% end %>
          </div>


          <%= link_to content_tag(:span, '', class: "glyphicon glyphicon-trash"), book_path(catal.books.first), method: :delete  %>
        </div>


      <% end %>
  </div>

 

app/views/users/edit.html.erb
<div id="edit_user_form">
  <%= simple_form_for(@user, html: { class: '' }) do |f| %>
  <%= f.input :name, placeholder: @user.name %>
  <%= f.input :email, placeholder: @user.email %>
  <%= f.input :department, placeholder: @user.department %>
  <%= f.input :course, placeholder: @user.course %>
  <%= f.input :yearofjoining, label: 'Year of joining', placeholder: @user.yearofjoining %>
  <%= f.input :hostel, placeholder: @user.hostel %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="row users_page">
  <%= will_paginate  style: 'margin-left:65px' %>
  <div class=" row section users_section">
      <%= render partial: 'users/user'  %>
  </div>
  <%= will_paginate style: 'margin-left:65px' %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag(@user.photo)  %>     
    </div>
    <div class="col-md-8">
      <span class="user_profile"><h4><%= @user.name %></h4><br>Department: <%= @user.department %>
      <br> Year Of Joining: <%= @user.yearofjoining %><br>Course: <%= @user.course %><br>Hostel: <%= @user.hostel %> <br> Owns   <%=@user.books_count.to_i==0 ? ("0 books") : (@user.books_count.to_i==1 ? ("1 book"):(@user.books_count.to_s + " books")) %>   </span> 
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row user_center_box">
    <div class="col-md-6">
      <%= image_tag(@user.photo)  %>     
    </div>
    <div class="col-md-6">
      <span class="user_profile"><h3><%= @user.name %></h3><br>Department: <%= @user.department %>
      <br> Year Of Joining: <%= @user.yearofjoining %><br>Course: <%= @user.course %><br>Hostel: <%= @user.hostel %> <br> Owns   <%=@user.books_count.to_i==0 ? ("0 books") : (@user.books_count.to_i==1 ? ("1 book"):(@user.books_count.to_s + " books")) %>   </span> 
    </div>
  </div>
    <div class="row books_owned">
      <h3 style = 'color:#fff'>Books Owned</h3>
      <% @cat.each do |cat| %>
        <div class="col-md-3 col-lg-2 col-sm-3 col-xs-2 front" >
          <div class="ih-item square effect11 top_to_bottom" id="first"><%= link_to catalogue_path(cat) do %>
            <div class="img" id="second"><%= image_tag cat.photo %></div>
            <div class="info" id="third">
              <h3><%= cat.title %></h3>
              <p>Author: <%= cat.author %><br>Language: <%= cat.language %>
                  <br>Length: <%= cat.pages %> pages<br>Owned by:<%= Book.all.where(catalogue_id: cat.id).length %> People<br>Add to Wishlist</p>
            </div>
          <% end %>
          </div>
        </div>
      <% end %>      
  </div>
</div>